namespace TankWars.Runtime.Gameplay.Enemy
{
    // This file is auto generated from the LevelId Scriptable Object
    // DO NOT EDIT THIS FILE MANUALLY
    public enum EnemyType
    {
        NONE,
        COPPER,
		SILVER,
		GOLD,
    }
}