namespace TankWars.Runtime.Core.UI.Buttons
{
    // This file is auto generated from the LevelId Scriptable Object
    // DO NOT EDIT THIS FILE MANUALLY
    public enum ButtonId
    {
        NONE,
        LOAD_LEVEL,
		SHOW_MENU,
		TANK_COLOR,
		GAME_DIFFICULTY,
		MUSIC_SLIDER,
		SOUND_EFFECTS_SLIDER,
		PAUSE_GAME,
		UNPAUSE_GAME,
		RESTART_GAME,
    }
}