namespace TankWars.Runtime.Core.Audio
{
	public class SoundID
	{
		// This file is auto generated from the LevelId Scriptable Object
		// DO NOT EDIT THIS FILE MANUALLY
		public const string BULLET_SHOOT = "BulletShoot";
		public const string BULLET_EXPLOSION = "BulletExplosion";
		public const string BACK_GROUND_SONG = "BackGroundSong";
	}
}

